---
deployment:
  tasks:
    - export DEPLOYPATH=/home/anaphwto/repositories/Anaplian-WP
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp styles.css-.color-bar $DEPLOYPATH
    - /bin/cp styles.css-.color-bar.color-segment $DEPLOYPATH

    
