---
deployment:
  tasks:
    # Create a virtual environment named "venv"
    - python3 -m venv venv
    
    # Upgrade pip and install dependencies from requirements.txt
    - venv/bin/pip install --upgrade pip
    - venv/bin/pip install -r requirements.txt
    
    # Touch the WSGI file to trigger Passenger to reload your app (ensure this file imports your app)
    - touch passenger_wsgi.py

    
